language: objective-c

osx_image: xcode8

install:
  - mkdir -p /Users/travis/build/facebook/.nvm
  - export NVM_DIR="/Users/travis/build/facebook/.nvm"
  - brew install nvm
  - source $(brew --prefix nvm)/nvm.sh
  # TODO npm 2 started stalling on Travis, t11852928
  - nvm install 5
  - rm -Rf "${TMPDIR}/jest_preprocess_cache"
  - wget https://github.com/yarnpkg/yarn/releases/download/v0.16.0/yarn-0.16.0.js
  - export yarn="node $(pwd)/yarn-0.16.0.js"
  - $yarn install

script:
  - if [[ "$TEST_TYPE" = objc-ios ]]; then travis_retry travis_wait ./scripts/objc-test-ios.sh; fi
  - if [[ "$TEST_TYPE" = objc-tvos ]]; then travis_retry travis_wait ./scripts/objc-test-tvos.sh; fi
  - if [[ "$TEST_TYPE" = e2e-objc ]]; then node ./scripts/run-ci-e2e-tests.js --ios --js --retries 3; fi
  - if [[ "$TEST_TYPE" = js ]]; then npm run flow check; fi
  - if [[ "$TEST_TYPE" = js ]]; then npm test -- --maxWorkers=1; fi

env:
  matrix:
    # - TEST_TYPE=e2e-objc

    - secure: ugxWaEVYDp/TOVX7eiQipyhAKxcjVyece7F+SEa5or5aJJPkp3TsLXlASMit3wDbqPTQrEiKrKDL+VC4O+qdcKX2INZ5R1xzXPejxUkfWrZF2iHvNyxC3fenaJG1mP+q9179zlNiiUtqic35tfk7WopxM/sMchNncXuVSlHzIsP1qknrk6pDvOHSLLtjTUiwxMEulLD3a+0k6c2eS4ZqTOgS+k4dJVjP7KnVJ5+hnsNbfVrPZvx0ycTXs5cjysFVaNINRPD2W+Ok5Qxceex02kWq/Tidd8dydhuvAjF2M0YeMEglRzLqAIMVz+BByLN/xUU54N8U+NZ7+a3Ds0pXXJ7IrTSLsq/9xJVlNmrmeF+I6u0A8hxalMqYR1a5GlDfpXUFR7cktRmNZNJqda87dU3M2QdMDWlN8ogWyMV9T0KT4eTKzPbOTAoRREqrNBFxy127mJSSqlGYs+swsHT28BaDRiGf3IYkL/N+E7BaOQsfo9TNAUlGk3uVSLfA4/PUYpMaQizr3YiElHaoD9aJtUXTdglBpbt7gvWUA4TBJC93F8DzwYugXe5uol3NwCOybVVf3Xxoxu8u0EIb6jisFxEc/kqg/8BEA52JcB3ipD0gtmwAf7uNjWgvJA3YAk3z7p00kgAke5JbNv4vczek2ilPicPx3MpNzNkhcIkZQSM=
    - TEST_TYPE=objc-ios
    - TEST_TYPE=objc-tvos
    - TEST_TYPE=js

branches:
  only:
    - master
    - /^.*-stable$/

notifications:
  email:
    recipients:
      - bestander@gmail.com
    on_failure: change
    on_success: change
